apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: hin-vmware-catalog
  description: A catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./components/tap-gui.yaml
    - ./groups/default-org.yaml
    - ./systems/tap-gui-system.yaml
    - ./domains/tap-gui-domain.yaml
    - https://github.com/hinyinlam/hin-tap-demo/blob/main/catalog/catalog-info.yaml
