apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: palm-machine-learning
  title: An RESTFul API for abstracting both incremental learning and inferening of palm reading
  description: This component mainly interact with user to visualize palm reading result
  tags:
    - v1alpha1
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=backstage'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: group:fortune-tellers
  system: palm-reading-system
  dependsOn:
    - component:palm-ml-incremental
    - component:palm-ml-inference
